package infrastructure

import (
	"database/sql"

	"github.com/dmitrymomot/go-test-task-management-tool/app/interfaces/repositories"
	_ "github.com/go-sql-driver/mysql" // init mysql driver
)

// NewMySQLHandler is a factory function,
// returns a new MySQLHandler struct instance
func NewMySQLHandler(dbSourcePath string) *MySQLHandler {
	conn, err := sql.Open("mysql", dbSourcePath)
	if err != nil {
		panic(err)
	}
	if err = conn.Ping(); err != nil {
		panic(err)
	}
	return &MySQLHandler{conn}
}

// MySQLHandler struct
type MySQLHandler struct {
	conn *sql.DB
}

// Execute a query without returning any rows.
// The args are for any placeholder parameters in the query.
func (h *MySQLHandler) Execute(query string, args ...interface{}) (repositories.DbResult, error) {
	smth, err := h.conn.Prepare(query)
	if err != nil {
		return nil, err
	}
	result, err := smth.Exec(args...)
	if err != nil {
		return nil, err
	}
	return &MySQLResult{result}, nil
}

// Query executes a query that returns rows, typically a SELECT.
// The args are for any placeholder parameters in the query.
func (h *MySQLHandler) Query(query string, args ...interface{}) (repositories.DbRows, error) {
	rows, err := h.conn.Query(query, args...)
	if err != nil {
		return nil, err
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return &MySQLRows{rows}, nil
}

// QueryRow executes a query that is expected to return at most one row.
// QueryRow always returns a non-nil value. Errors are deferred until
// Row's Scan method is called.
// If the query selects no rows, the *Row's Scan will return ErrNoRows.
// Otherwise, the *Row's Scan scans the first selected row and discards
// the rest.
func (h *MySQLHandler) QueryRow(query string, args ...interface{}) repositories.DbRow {
	row := h.conn.QueryRow(query, args...)
	return &MySQLRow{row}
}

// Close closes the database, releasing any open resources.
func (h *MySQLHandler) Close() error {
	return h.conn.Close()
}

// MySQLRow structure
type MySQLRow struct {
	rows *sql.Row
}

// Scan copies the columns in the current row into the values pointed
// at by dest. The number of values in dest must be the same as the
// number of columns in Rows.
func (r *MySQLRow) Scan(dest ...interface{}) error {
	return r.rows.Scan(dest...)
}

// MySQLRows structure
type MySQLRows struct {
	rows *sql.Rows
}

// Scan copies the columns in the current row into the values pointed
// at by dest. The number of values in dest must be the same as the
// number of columns in Rows.
func (r *MySQLRows) Scan(dest ...interface{}) error {
	return r.rows.Scan(dest...)
}

// Next prepares the next result row for reading with the Scan method
func (r *MySQLRows) Next() bool {
	return r.rows.Next()
}

// MySQLResult structure
type MySQLResult struct {
	result sql.Result
}

// LastInsertId returns the integer generated by the database
// in response to a command. Typically this will be from an
// "auto increment" column when inserting a new row. Not all
// databases support this feature, and the syntax of such
// statements varies.
func (r *MySQLResult) LastInsertId() (int64, error) {
	return r.result.LastInsertId()
}

// RowsAffected returns the number of rows affected by an
// update, insert, or delete. Not every database or database
// driver may support this.
func (r *MySQLResult) RowsAffected() (int64, error) {
	return r.result.RowsAffected()
}
