version: "3"

services:
  app:
    container_name: "testapp"
    build:
      context: .
      dockerfile: Dockerfile
    image: testapp
    ports:
        - "8080:8080"
    depends_on:
      - db

  db:
    container_name: "testapp_db"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  pma:
    container_name: "testapp_pma"
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MAX_UPLOAD: "512M"
    ports:
      - "8081:80"
    depends_on:
      - db
